### ISSUE TITLE
io.netty.util.internal.OutOfDirectMemoryError

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Waterfall#121]
when players switch servers or try to join the server they get this error: http://pastebin.com/raw/wF77t0wd

screenshot of kick message for client: https://gyazo.com/1d56f08f7fd3d44974021f1a2e6ef11e

possibly related? https://github.com/netty/netty/issues/6221

**Comment by Black-Hole** [comment]
16 MB for a packet seems pretty high. That large packets I could think of would be chunk or scoreboard team packets.

**Comment by PhanaticD** [comment]
bump still having this issue

```
23:52:58 [SEVERE] [/IP:55598] <-> InitialHandler - encountered exception
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 15267266567, max: 15271460864)
    at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:585)
    at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:539)
    at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:760)
    at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:736)
    at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
    at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:320)
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
    at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:133)
    at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:80)
    at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:71)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1006)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by MarkTwoFive** [comment]
> failed to allocate 16777216 byte(s) of direct memory (used: 15267266567, max: 15271460864)

Do really host a Waterfall Instance which needs >15 Gigabytes of RAM just to fail allocating another 16 Megabytes? Maybe you should better take a look into that. Waterfall/BungeeCord in no way uses as much RAM as an actual Minecraft server.

**Comment by Techcable** [comment]
This almost certainly a memory leak. Please enable advanced leak detection by adding `-Dio.netty.leakDetectionLevel=advanced` to your startup flags.

**Comment by PhanaticD** [comment]
got this: the censor plugin was made by Pangea on IRC

https://gist.github.com/Techcable/c1def111b2c3e896f9404df82ace74eb

**MOD EDIT:** Moved log to gist

**Comment by oculus42** [comment]
I was running into this regularly on 1.16.5 (playing Vault Hunters) and found the flag `-Dio.netty.maxDirectMemory=0` was able to eliminate the issue with no obvious side-effects.

**Comment by Janmm14** [comment]
@oculus42 wrote:
> I was running into this regularly on 1.16.5 (playing Vault Hunters) and found the flag `-Dio.netty.maxDirectMemory=0` was able to eliminate the issue with no obvious side-effects.

I doubt this is useful to post under a 4 year old github issue where theproblem specifics were completely different.
I would also never give it unlimited maximum.

**Comment by Techcable** [comment]
> I was running into this regularly on 1.16.5 (playing Vault Hunters) and found the flag `-Dio.netty.maxDirectMemory=0` was able to eliminate the issue with no obvious side-effects.

**DO NOT POST ON ISSUES THIS OLD**

At least not without a **really** good reason.

## 1. The underlying issue is usually different, because the code has usually changed

This is almost certainly the case here.

> I doubt this is useful to post under a 4 year old github issue where theproblem specifics were completely different.

This. 💯  I can all but guarantee you the underlying issue you are having is different then PhanaticD was.  (See part 1 above)

The exception `io.netty.util.internal.OutOfDirectMemoryError` is an *extremely* vauge error. This is like posting `StackOverflowError` or `OutOfMemoryError`. These have 1000s of possible causes.

> found the flag -Dio.netty.maxDirectMemory=0 was able to eliminate the issue with no obvious side-effects.

As @Janmm14 said, is equivalent to setting an unlimited limit to netty's native memory. Imagine setting `-Xmx=unlimited`. While this technically works around "out of memory" netty issues (temporarily), it is *not* a good idea.

## 2. You end up pinging everyone involved in the original issue, even if they've fixed their problem (or stopped contributing to the project)

Like I said above, so you've pinged a bunch of people who are either:
- not interested in solution (either different problem, or left Minecraft)
- stopped contributing to the project
- not able to help because they're working on a different plugin (or have expertise in a different part of the codebase)

Personally, I am semi-retired from Minecraft. I am not actively involved in the Waterfall or Paper projects right now. I am focusing on school, other projects, and some very serious health problems. 

Yet you have pinged me and this response has taken a good 15 minutes to write 😉 Luckily I was busy procrasitnating from my homework, so there are no hard feelings. 😉  You had good intentions & open-source is a learning process ❤️ 

As for PhanaticD, I believe he has shut down his server and moved on from Minecraft. This is a sad loss for the community, but you also pinged him too.

## What you (@oculus42 ) should do instead

1. Please file a new issue giving more details on your underlying problem (full plugin setup, full stack trace, full server logs)
    - This is probably a plugin problem, but it could also be a serious problem with waterfall itself
2. Consider migrating to [velocity](https://velocitypowered.com) in the long-term. It is overallbetter designed than Bungee/Waterfall and likely fixes many of your issues
     - Bungee/Waterfall were good for their time, but we've learned & the technology has progressed 😉 

@electronicboy please lock this issue 🔒 

(I no longer have triage permission on Waterfall, and am not not sure how to ping the triage group, so unfortunately I had to resort to you 😺 )

**Comment by PhanaticD** [comment]
💀
