### ISSUE TITLE
"This build is outdated" but... I'm using the latest build.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [PaperMC/Waterfall#124]
```
*** Warning, this build is outdated ***
*** Please download a new build from https://ci.aquifermc.org/job/Waterfall/ ***
*** You will get NO support regarding this build ***
*** Server will start in 10 seconds ***
```
I tried redownloading the latest build from https://ci.destroystokyo.com/job/Waterfall/101/ and I had the same issue.

**Comment by jamierocks** [comment]
The problem here, is the stupidity of how outdated builds are determined.
What I'll do is pull the Bungeecord changes giving you a build to update too.

**Comment by MrPowerGamerBR** [comment]
@jamierocks yeah, after taking a look at how BungeeCord determines if a build is outdated or not... it is a bit strange, what if nobody submits a new commit to BungeeCord for more than 28 days?

**Comment by jamierocks** [comment]
Exactly why I'm leaving this issue open as so I can investigate alternate methods of establishing if a build is our of date.

**Comment by MrPowerGamerBR** [comment]
@jamierocks instead of checking if the build is X days old, couldn't you check if the build is X commits behind? (like how Paper shows how many versions are you behind when using /version)... (but I don't think this is the perfect solution)

**Comment by jamierocks** [comment]
What are the thoughts on this solution?

Change the message to:
```
*** Hey! This build is potentially outdated :( ***
*** Please check for a new build from https://ci.destroystokyo.com/job/Waterfall/ ***
*** Should this build be outdated, you will get NO support for it. ***
*** Server will start in 10 seconds ***
```

**Comment by Rushmead** [comment]
Could we make the time shorter? Maybe add an parameter to disable it as well, because if you're running a server where it is version dependent it is a pain to have to wait every time it boots.

**Comment by jamierocks** [comment]
Well the delay is to ensure that the server admin sees the message. I agree it may be a pain for some. How about 5 seconds?

**Comment by Rushmead** [comment]
Yeah that'll be fine :)

**Comment by MarkTwoFive** [comment]
@jamierocks Just that many server admins don't look at the console live though ^^

I'd recommend a switch to knowingly turn this delay off in production environments.

**Comment by jamierocks** [comment]
The ones who don't look at it live aren't the people who the message is targeting :p

**Comment by MarkTwoFive** [comment]
@jamierocks Yeah but those are the ones even more annoyed by any unnecessary delay.

**Comment by jamierocks** [comment]
- **User perspective:** I can see the slight nuisance caused by the delay, but it is not a major length of time.
- **Waterfall Dev Perspective:** We need all of our users to be using up-to-date software, if it annoys them that's good - we have their attention.

---

> unnecessary delay

The delay really isn't unnecessary - it is a rather insignificant period of time to wait, which can ensure server administrators are using the latest software. By doing this server administrators not only benefit themselves, but ourselves (Waterfall team) too.

---

I am reluctant to provide a config toggle for this as I would imagine the majority of people who use this are going to be the ones annoyed by the delay. Which I would imagine are the people who do not update their software either.

**Comment by MarkTwoFive** [comment]
@jamierocks Then at least make it depending on actual updates being available - not just some™.
Systems like ours use patchdays and having software adding annoying delays just because it doesn't line straight up with it is potentially annoying so we'll be either hot-swapping or just patching that out in an own branch. Which both are just slightly op for something like a "potential" code commit.

**Comment by jamierocks** [comment]
The message exists as a mechanism to provide support to our users, the delay exists to ensure that the message is hopefully read. Providing a configuration option for the delay, would cause it to be disabled by everyone who gets annoyed at the delay - which makes the message useless as it will never get seen.

We acknowledge that 5 seconds is a nuisance in terms of delay to starting your network, however IMO 5 seconds is quite frankly nothing to the time it takes for a MC server to start.

As far as your quote about patching it yourselves - go ahead, that's the great thing about open-source projects is that people can make their own modifications. But quite frankly I do not see the necessity for a fork to be make for this.

Bungee has employed this system for quite some time, and the only time is is annoying is when there isn't a newer build available. In saying that, perhaps it is best to look at improving the detection of outdated builds.

**Comment by Janmm14** [comment]
BungerCord provides a system environment flag to disable the old build checking: `-DIReallyKnowWhatIAmDoingISwear=true`

**Comment by MarkTwoFive** [comment]
That's what I was thinking about

**Comment by Rushmead** [comment]
I did suggest this but no response was given

**Comment by jamierocks** [comment]
Having implemented the suggestions I made earlier, I am going to close this issue.
