### ISSUE TITLE
[Feature Request] Update Folder

### ISSUE THREAD

**Issue by PatoTheBest** [PaperMC/Waterfall#196]
Add an update folder just like in bukkit. When waterfall restarts, it will then replace the jars in the plugins directory with the jars from the update folder.

**Comment by jamierocks** [comment]
This seems rather useless to me, perhaps I don't understand it. What I took from what you said is that there is a temporary directory, that is scanned as the proxy starts for plugins, should any exist, the plugins directory is cleared, and the plugins found are moved to the correct directory.

**Comment by mikroskeem** [comment]
This is pretty good idea actually. Bukkit moves plugins with same filename from update folder to parent (iow plugins) directory on startup. That eases plugin updating for server administrators and/or adds ability for plugins to implement self-update in easy way.

**Comment by PatoTheBest** [comment]
@jamierocks Yeah, but is really useful for deploying updates

**Comment by jamierocks** [comment]
So, it only replaces files of the same name?

**Comment by electronicboy** [comment]
Yup; basically any file inside of the update folder will be copied over to the plugins folder, from SimplePluginManager

```
    private void checkUpdate(File file) {
        if (updateDirectory == null || !updateDirectory.isDirectory()) {
            return;
        }

        File updateFile = new File(updateDirectory, file.getName());
        if (updateFile.isFile() && FileUtil.copy(updateFile, file)) {
            updateFile.delete();
        }
    }
```
This method is called inside loadPlugin just before the plugin is actually loaded inside that method

**Comment by MarkTwoFive** [comment]
I don't really get the point of that. Why not place the plugins in the plugin directory in the first place?

**Comment by mikroskeem** [comment]
> That eases plugin updating for server administrators and/or adds ability for plugins to implement self-update in easy way.

1) Plugin self-updates cannot be done easily: jar shouldn't be replaced on runtime and plugin cannot self-update in sane way (I have a lot of weird ideas, let's keep them aside right now).
2) Eases server administrator life: instead of stop-replace-start, you can just drop file to updates folder and restart - which is of course faster.

**Comment by MarkTwoFive** [comment]
1. I'm not really into self-updates in a highly versioned game like Minecraft but I get what the intention is.

2. You can already do that under Linux :)

**Comment by MarkTwoFive** [comment]
Also keep in mind that keeping the version number in your file name can be very useful and is not easily possible with simple self-update mechanisms.

**Comment by electronicboy** [comment]
Honestly, I don't feel this change is really suitable here unless plugin authors are going to be shoving waterfall down peoples throats instead of bungee, has this been proposed upstream?

It would be kinda weird to have a feature in a fork, which if you want you can easily replicate the behavior of inside of a shell/batch file, where plugin authors aren't really going to take advantage of it due to the fact that it's only available here.

**Comment by smmmadden** [comment]
I agree with others here.  I host and manage 10 servers and monitor hundreds of plugins in the spigot community and I have yet to see one plugin that will automatically update itself.  The rule of thumb is that developers add "a check version" and notify the server admins when a new version may be ready.  Not everyone does this of course but it is becoming more and more common practice.

As @MarkL4YG  stated, the version/build number as part of the jar file is very helpful and I have been doing it that way since day one.  It tells me by glimpsing thru the 50+ plugins on each server which ones need updating based on watch notifications I'm on.

That said, I do use a plugin called PlugMan which does allow you to unload and load up a new versioned plugin while the server is live.  It does a pretty good job but not infallable because of how the API's are constantly changing in Spigot, Craftbukkit, Forge, Minecraft etc.  It's a trickle down change that almost always breaks many of the plugins.  In these cases, 99% of them require a server shutdown and swap out of the later version of the plugin and/or configuration or permission changes that come with it.  In fact, most developers highly recommend this and for good reason.  So there isn't an easy solution and backward compatibility is never guaranteed.  So it is a plugin by plugin update process and one size does not fit all in this environment (at least not yet).

**Comment by smmmadden** [comment]
I should note that using Waterfall instead of Bungee offers many advantages.  It is updated more frequently and it does allow to have a network of servers to let players teleport between them with the right plugins and it also allows players to use a sponge forge mod and client connecting to both Forge and Spigot servers with ease.  That's a win-win that Bungee doesn't support yet.

**Comment by mikroskeem** [comment]
> You can already do that under Linux :)

> you can easily replicate the behavior of inside of a shell/batch file

Wouldn't that feature be more convenient to be built in though? Why was it implemented in Bukkit at first place if that can be done with scripting instead? :thinking: 

>I agree with others here. I host and manage 10 servers and monitor hundreds of plugins in the spigot community and I have yet to see one plugin that will automatically update itself. The rule of thumb is that developers add "a check version" and notify the server admins when a new version may be ready. Not everyone does this of course but it is becoming more and more common practice.

If you talk about community plugins, then I have to agree with you - \*random\* plugin updates without backwards compatibility can be bitch to fix.

On the other hand if you create plugins on your own and mass deploy them to network's servers, then update folder is extremely useful and I have to disagree with people here who don't want given feature to be implemented.

**Comment by MarkTwoFive** [comment]
If you create plugins mass deploying them on a network you'll probably already have a bunch of utility scripts running. Which renders an implementation of this useless anyways as you can easily accomplish this using bash/sh scripts. Even in Batch this shouldn't be that hard.

**Comment by MarkTwoFive** [comment]
I also deployed an enormous amount of servers in the past but I can't remember ever using that feature in Bukkit once.
I also don't expect automatic updates to be really transparent to the most of the userbase for Minecraft server frameworks as most of them will only realize the existence of such a feature when it eventually breaks their server...

Subjective opinion following:
I already hate that update delay of BC/Waterfall whenever an update is available but automatic updates of any kind could make things even worse.

**Comment by mikroskeem** [comment]
> If you create plugins mass deploying them on a network you'll probably already have a bunch of utility scripts running. Which renders an implementation of this useless anyways as you can easily accomplish this using bash/sh scripts.

\<offtopic\>
Tbh not specifically bunch utility scripts, I have made dedicated companion daemon to manage server updates etc. 
\</offtopic\>


> I also don't expect automatic updates to be really transparent to the most of the userbase for Minecraft server frameworks as most of them will only realize the existence of such a feature when it eventually breaks their server...

> I already hate that update delay of BC/Waterfall whenever an update is available but automatic updates of any kind could make things even worse.

Why are you thinking that everyone will start using given feature? I really doubt it as even on Bukkit, only few plugins do that. For example:
- FAWE does automatic update by default, but that can be turned off
- PlotSquared notifies you about update and user can download an update with command, file ends up in `updates` folder.

> Honestly, I don't feel this change is really suitable here unless plugin authors are going to be shoving waterfall down peoples throats instead of bungee, has this been proposed upstream?

I think it'd be better to submit PR to upstream at this point, as upstream changes end up in Waterfall anyway. This arguing keeps going on otherwise.

**Comment by mikroskeem** [comment]
https://github.com/SpigotMC/BungeeCord/pull/2314

**Comment by PatoTheBest** [comment]
@mikroskeem Thanks!

**Comment by Janmm14** [comment]
> I already hate that update delay of BC/Waterfall whenever an update is available but automatic updates of any kind could make things even worse.
>
> _from @MarkL4YG_ 

You can disable it with a cli flag. I think it was `-Direallyknowwhatiamdoingiswear`

**Comment by MarkTwoFive** [comment]
@Janmm14 Oh, I wasn't aware of that. Thanks for the info. And - yes - I know what I'm doing ;)

**Comment by jamierocks** [comment]
If someone wants to go about writing a non-obtrusive, easy to maintain, pull request that implements this functionality - I will consider merging it.

Else, I'm with md_5 on this one.
