### ISSUE TITLE
Scoreboard. Error after player respawn. Sponge.

### ISSUE THREAD

**Issue by SawFowl** [PaperMC/Waterfall#212]
I use a static Scoreboard with automatic update of values on the timer. I'm using a server with Sponge API.

After respawn, when the scoreboard is updated, player is thrown from the server, and the following error appears in the BungeeCord console.
https://pastebin.com/kf6UppCz
If you connect directly to the Sponge server (without using WaterFall), then the problem does not arise.

**Comment by MarkTwoFive** [comment]
Did you check wether or not this happens in BungeeCord too? If so you'd report to them instead.

**Comment by SawFowl** [comment]
I reported, but they refused to correct it.
https://github.com/SpigotMC/BungeeCord/issues/2366
I hope that at least your team will fix. The original BungeeCord also does not allow you to connect to Forge servers, and you implemented it.

**Comment by electronicboy** [comment]
Bungeecord, and by extension Waterfall, requires tracking stuff like scoreboards properly, your issue here is that you're redefining an objective that already exists, although the objective doesn't exist on the new server until you're creating it, you're sending it while to the client the existing version is still defined, as bungeecord hasn't been able to clean that up yet.

It's not really possible to fix this here (Bungeecord needs to be able to handle cases where they didn't connect to the new server, removing objectives too early would cause a crash should the server send data for objectives that don't exist).

I would suggest adding some random text to the objective name internally so that you can ensure that they don't match up across server instances.

**Comment by SawFowl** [comment]
I can make a random name for the scoreboard, but in this case I get a memory leak. Thanks for the info.

**Comment by MarkTwoFive** [comment]
I'd recommend naming scoreboards using uuids in this case.
As for the memory leaks: Maybe you can find a way to destroy the old scoreboard objects when a player respawns.

**Comment by SawFowl** [comment]
If I had found a way to delete the old values of the scoreboard, I would not have to write here.

**Comment by MarkTwoFive** [comment]
Reporting an issue does not require you to not have a work-around. ^^
