### ISSUE TITLE
SevTech: Ages Fire Stick not working

### ISSUE THREAD

**Issue by MrKitty871** [PaperMC/Waterfall#239]
Hello,
I have never submitted an issue on github before and apologize if I am not giving enough info. If there is any more info I can give please let me know and I will reply as quickly as possible.

Details:
I have a SevTech: Ages 3.0.8 server running with the latest waterfall build
I changed the forge version of SevTech from 5707 to 5705 to be compatible with spongeforge
I have spongeforge BETA-3217 installed

Issue:
With everything configured and working together everything seemed to work just fine. Until you get to the fire stick portion of the modpack, what you have to do is have a fire stick in your off hand as well as your main hand and right click the ground somewhere. This is supposed to create a fire similar to flint and steel. The fire sticks do their animation but no fire is spawned. I have narrowed the issue down to the bungeecord module being on in the sponge config. When I turn bungeecord integration off everything works perfectly. There are no error logs in either terminal when trying to use the fire sticks.

**Comment by jamierocks** [comment]
Just to confirm, does this only happen when playing through the proxy? As in, the issue isn't present if you were to directly connect to the server?

**Comment by electronicboy** [comment]
Bungeecord on or off in the server would have no impact whatsoever on how bungee interacts, it working when turned off (assuming that you're still connecting via the proxy) would indicate that the mod has some incompatibility issues around bungeecord mode for some reason

One potential test around if it is an incompatibility is to throw up a waterfall instance in offline mode and test it (that would allow you to test a few discrepancies which some mods might have around UUIDs and the servers online mode being a bit outta sync), i wouldn't imagine this to have any form of behavior change, but it is a quick and worthwhile test

**Comment by MrKitty871** [comment]
@jamierocks I was going to test it out before replying but I am having some issues setting the right settings to let me connect directly. It is telling me "If you wish to use IP forwarding, please enable it in your BungeeCord config as well" when it is already enabled.

@electronicboy I tried your suggestion and got the same results

**Comment by electronicboy** [comment]
So;

proxy in offline mode with bungeecord on = fail
proxy in online mode with bungeecord on = fail
proxy in online mode with bungeecord off = works

correct?

in order to connect directly to the server to test, you'd need to disable bungeecord mode on the server, otherwise, it won't see the bungeecord information and will close the connection (with that message)

**Comment by MrKitty871** [comment]
"proxy in online mode with bungeecord off" wouldn't that just be the standalone server?
If that is the case then yes, when bungeecord is disabled the issue is non existent

**Comment by electronicboy** [comment]
By bungeecord I mean bungeecord mode, should have expanded upon that, but I mean, still connecting via the proxy but with the setting turned off on sponge itself

**Comment by MrKitty871** [comment]
From what I can tell if bungeecord is disabled in sponge then I am unable to connect to the server through the proxy

**Comment by MrKitty871** [comment]
But of course I can connect directly at that point, also at that point everything seems to work perfectly. The fire stick works fine

**Comment by electronicboy** [comment]
I'm trying to clarify if you've tested with bungeecord without the setting being enabled inside of the server, (this would work, just IP and UUID wouldn't be set properly on the players), or if by "the bungeecord module being on in the sponge config" you mean that "without the bungeecord setting being enabled in sponge AND directly connecting"

If you mean it works fine without bungeecord mode being enabled in sponge while connecting via the proxy, your issue is either going to lie with the mod providing that feature or with sponge

**Comment by MrKitty871** [comment]
I understand, so it really has nothing to do with waterfall
