### ISSUE TITLE
Error with latest version

### ISSUE THREAD

**Issue by NeximaOzi** [PaperMC/Waterfall#250]
Hello,
I'm getting this error.
https://hastebin.com/tonogatoco.bash

**Comment by electronicboy** [comment]
You're more than likely trying to connect with a client version which is currently unsupported

**Comment by NeximaOzi** [comment]
so it is not problem ? just a player trying connect unsupported client version just this ?

**Comment by NeximaOzi** [comment]
Ticket closed but my problem not solved still i'm get this error;
https://hastebin.com/debagonafe.bash

**Comment by JorisPV** [comment]
@NeximaOzi Update your Waterfall : https://github.com/WaterfallMC/Waterfall

**Comment by jamierocks** [comment]
As far as we can tell, this only happens when a player tries to connect using a MC version not supported by Waterfall.

edit: Though looking at that newer stacktrace, `455420687474703a2f2f7777772e3132336368612e636f6d20485454502f312e310d0a486f73743a207777772e3132336368612e636f6d0d0a50726f78792d43` is strange input - perhaps you're being botted.

**Comment by NeximaOzi** [comment]
@jamierocks what i need ?

**Comment by jamierocks** [comment]
No idea, there was discussion in https://github.com/WaterfallMC/Waterfall/issues/251 though
