### ISSUE TITLE
error pinging remote server

### ISSUE THREAD

**Issue by VenixMC** [PaperMC/Waterfall#274]
https://hastebin.com/kikizeviju.bash

**Comment by MarkTwoFive** [comment]
Very low on information imo.  
Verify that the Waterfall server is able to reach the MC server.
Check address, ports, network, firewall etc.

**Comment by electronicboy** [comment]
`Caused by: java.net.ConnectException: Connection refused: no further information`
The connection to the server was refused by your server or firewall, check your network configuration is setup properly, the backend server is running and listening on the correct port, and that your firewall is allowing traffic
