### ISSUE TITLE
Waterfall logger / terminal does not properly handle / hide debug level OFF.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Waterfall#278]
Waterfall dev 218

RE: https://github.com/Phoenix616/ResourcepacksPlugins/issues/15#issuecomment-414688195

**Comment by stephan-gh** [comment]
This works as intended. `Level.OFF` is not supposed to be used for logging messages; it only exists for `Logger.setLevel` etc to suppress logging on **all** levels.

That's why it is implemented as the highest possible logging level (`Integer.MAX_VALUE`), much more "important" than `Level.SEVERE`, so if someone really does log at that level the message should be considered like the most fatal error ever possible. (Essentially complete universe destruction or even worse!).

BungeeCord logs it too:

```
21:05:37 [OFF] [BungeeResourcepacks] 
21:05:37 [OFF] [BungeeResourcepacks]   If you enjoy my BungeeResourcepacks plugin then you might also be
21:05:37 [OFF] [BungeeResourcepacks]   interested in the more advanced ForceResourcepacks version!
21:05:37 [OFF] [BungeeResourcepacks] 
21:05:37 [OFF] [BungeeResourcepacks]   Besides getting additional features like WorldGuard support and
21:05:37 [OFF] [BungeeResourcepacks]   the ability to force a player to accept the resources pack you
21:05:37 [OFF] [BungeeResourcepacks]   will also support the continued development of this plugin!
21:05:37 [OFF] [BungeeResourcepacks] 
21:05:37 [OFF] [BungeeResourcepacks]   Check it out here on spigotmc.org: https://s.moep.tv/frp
21:05:37 [OFF] [BungeeResourcepacks] 
21:05:37 [OFF] [BungeeResourcepacks]   - Phoenix616
21:05:37 [OFF] [BungeeResourcepacks] 
```
