### ISSUE TITLE
Client get's "this connection is terminated"

### ISSUE THREAD

**Issue by NightScale5755** [PaperMC/Waterfall#288]
I don't know if it's Project Portals or Waterfall. but whenever I try to teleport between servers, using a portal or sign, my console get a ton of errors, and my client gets "A fatal error has occurred, this connection is terminated"
Please and thank you.

[latest.log](https://github.com/WaterfallMC/Waterfall/files/2410703/latest.log)

**Comment by NightScale5755** [comment]
oh, shoot, sorry about that, but I forgot to mention: I am using spongeforge 1.12.2, and the error is at the bottom of the log. Plus, tell me if you need anything else.

**Comment by electronicboy** [comment]
Sorry for the delay, however closing: This issue is caused by `com.gmail.trentech.pjc.core.BungeeManager.lambda$getServer$18(BungeeManager.java:86) ~[BungeeManager.class:?]`
That plugin is attempting to teleport a player off the main thread and is causing issues as this is unsafe and improper behavior which sponge is throwing an exception over this
