### ISSUE TITLE
Console issue: maybe a listener issue?

### ISSUE THREAD

**Issue by x1p** [PaperMC/Waterfall#305]
I'm trying to replace Bungee by Waterfall. However I run into this issue.

When I restart Waterfall, I can see the console output on my hosting page.

When I switch to a different console screen and come back later, the console output is gone until I perform a command or restart. So the console seems to forget what happened before.

The console page of the hosting provider is something like multicraft, but different. I filed an issue at the hosting provider. They are still searching for the cause.

BungeeCord works fine. Waterfall has the same config settings. So nothing is changed there. It has to be something Waterfall does different which breaks the console.

Is there anybody that could identify what goes wrong here?

**Comment by electronicboy** [comment]
The only difference here is that Waterfall uses an updated terminal/logger implementation, the issue here would sound like their console implementation is doing something weird, there is no reason that output would disappear until you send a command, sounds like the console system they're using is just not handling terminal output properly

You could look into trying to see if they'll add `-Dterminal.jline=false` as a JVM argument to disable the fancy features of the terminal

**Comment by x1p** [comment]
The console returns to the last state it was in when using BC.
I'll pass this information to them. Maybe this contributes to it.

Thanks for the trouble.

**Comment by electronicboy** [comment]
Minecrell crept up and pointed something out, if they're reading the old log file in order to determine the existing output, this has been moved in waterfall as part of the logger changes, so that it now conforms to the same layout as used by paper and craftbukkit

A log4j config was provided which will use a logging setup similar to BC, (use `-Dlog4j.configurationFile=log4j2-bungee.xml` to enable it, or you could grab it out of the jar, remove the -bungee part and it should use that file as the default)

**Comment by x1p** [comment]
Can this be related?
> [16:12] Aikar: @james090500 query isnt suppose to be on same port as MC, thats your issue
> [16:12] Aikar: they are fighting for the port

**Comment by james090500** [comment]
I have been summoned.

But no this is in no way related. I was stupidly running query on the same port as MC when infact query doesn't even need to be enabled

**Comment by x1p** [comment]
Well I've got this what looked similar
```
[18:01:25 INFO]: Listening on /0.0.0.0:12345
(Daemon) Server marked as ON
[18:01:25 INFO]: Started query on /0:0:0:0:0:0:0:0%0:12345
```
Sorry I've mentioned you. Did not realize this is connected ;-)

**Comment by james090500** [comment]
This isn't why your host isn't reading the logs though. electronicboy already gave you an answer. The above error is trying to bind 2 processes to the same port.

**Comment by mikroskeem** [comment]
>query isnt suppose to be on same port as MC, thats your issue

wait what, query uses UDP and it can use same port as MC freely (which uses TCP).

**Comment by x1p** [comment]
Issue fixt by the hosting.
The issue was fixed due to the solution provided by Minecrell
