### ISSUE TITLE
Suggestion: Glist

### ISSUE THREAD

**Issue by x1p** [PaperMC/Waterfall#308]
I have a suggestion for the glist command

I would like to have the glist output to have in an order which is logical.
For example something like the order which they are stated in the config.

This makes it for staff better, easier and more quickly to interpret it and understand.

**Comment by electronicboy** [comment]
The included modules are designed to be as barebones as possible to do the job, if you want customization (if you note, none of those modules provide any configuration options whatsoever, the reconnect_yaml module does access the config to provide a default reconnct handler, but that's general plugin-like behaviour, and a somewhat cleaner way for bungee to provide this without it being some hidden inaccessible internal class), you should look into using a plugin to replace the command

Also, it's worth noting that the API does not expose the order of which servers are defined in the config, that information is actually lost when the map is populated properly due to the usage of a hashmap, I guess we could consider replacing that, but that's not a high priority task

**Comment by x1p** [comment]
Ok maybe alphabetical might me an option.
