### ISSUE TITLE
Blocks arent connected

### ISSUE THREAD

**Issue by tomkeuper** [PaperMC/Waterfall#311]
I just updated to the latest version of waterfall and when I join my server the glass panes are not connected to the blocks anymore only when i replace the wool that it should be connected to it will connect again but if i relog its not connected anymore. http://prntscr.com/lkvxtr 
I am not certain if this is caused by waterfall but I did not have this problem before.
The server version of the lobby is 1.8

**Comment by electronicboy** [comment]
When using protocol hacks, it's 100% down to the protocol hack to re-implement features in newer versions, such as block connections. They work on placement because the client knows that they should be connected, but on reconnection, the server needs to send that information. ViaVersion has a beta option for this, not too sure about others.
