### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Lunatik934** [PaperMC/Waterfall#341]
Hey, sometimes players was kicked with this message : 

https://proxy.spigotmc.org/60e30616962e327b48e19e4b06f76d2c1616362a?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F361927406694694924%2F534023642070253584%2Funknown.png

when I use : https://www.spigotmc.org/resources/■-jpremium-2-0-■-advanced-login-system-with-auto-login-premium-players-■-1-8-1-13-■.27766/

I have speak with the dev of this plugins and he say me : https://puu.sh/Cx97Z/710e32073a.png

Please fix <3

**Comment by electronicboy** [comment]
As the author of the plugin has stated, this is caused by the server sending an invalid packet, nor can the author replicate the issue with waterfall, leading to suggest that it's completely irrelevant to that plugin or waterfall.

Nor can we also provide support around premium plugins, we do not have access to the software, meaning that we cannot replicate these issues

**Comment by kamcio96** [comment]
From spigotmc.org:
Required:
- **BungeeCord server (only BungeeCord engine, without modification)**
- MySQL database
- Java 8 or higher
- Internet connection
