### ISSUE TITLE
so 10-20 minute crash to hub

### ISSUE THREAD

**Issue by D4rkHelix** [PaperMC/Waterfall#348]
https://paste.feed-the-beast.com/view/f3b5c6b2 here is the pastebin even removing all the plugins its still happening can u please have a further investigation into it would be much appreciated. Like 10-20 minutes sometimes not even a minute crash to hub from po3 too the hub unsure why you may know a solution ill leave that upto you too see if u are willing to help 👍

**Comment by electronicboy** [comment]
`Caused by: io.netty.channel.unix.Errors$NativeConnectException: syscall:getsockopt(..) failed: Connection refused`
Means that the connection was refused by something upstream, given the timeouts, potentially a network issue

`java.lang.IllegalArgumentException: Unknown meta type 14`
in waterfall.yml, there is a configuration option to disable entity metadata rewriting

I got mixed up on the original issue, sorry; However, in the future, please make sure to provide *all* relevant log files, it makes finding issues and addressing them much smoother
