### ISSUE TITLE
Disabling item change animation on server change

### ISSUE THREAD

**Issue by danwillm** [PaperMC/Waterfall#414]
Hello,

I was wondering if there was  a way to disable the item change animation when switching servers? At the moment when I change servers, the `playOutHeldItemChange` packet gets sent, which looks like it triggers the animation... is there any way to disable it?

Thank you very much in advance.

**Comment by mikroskeem** [comment]
Why would you want to disable that exactly?

**Comment by Janmm14** [comment]
The new server is sending the last known cursor position of the hotbar for that player / the default one / the one set by a plugin on join.

**Comment by danwillm** [comment]
@Janmm14 could you help me as to tell me where that is?

Thank you very much.

**Comment by mikroskeem** [comment]
Intercept said packet, cancel sending and move handling to plugin installed on the proxy. Should be easily doable, just don't forget to keep slot state sync with backend servers (e.g via plugin messages - tell server about new slot state on join)

**Comment by danwillm** [comment]
Where am I able to intercept that packet? I've tried downstreambridge but doesn't seem to be working

**Comment by danwillm** [comment]
@mikroskeem 

Where would I be able to find the code to intercept this packet? I've tried downstreambridge.java but it doesn't seem that I can cancel it there.

**Comment by Janmm14** [comment]
you have to add a new packet in the protocol module and register it, and then in the proxy module you have to update the interface of downstreambridge for handling, and then you can handle it in downstreambridge

**Comment by electronicboy** [comment]
^ Bungee requires that packets are registered in order to be able to "intercept" them, otherwise, they're just passed straight through. Ultimately, the client was never really intended to be used like this, you could test if the disable entity metadata in waterfall.yml provides a nicer transfer experience given that it forces more client state to be in a "we're joining a server" vs "we're switching dimension", or try to control what the client is sent more as above
