### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown meta type 18 error in console

### ISSUE THREAD

**Issue by 123Kappa** [PaperMC/Waterfall#434]
Server randomly kicks people, here's the error in waterfall's console: https://pastebin.com/urAppz9W

I heard that enabling "disable_entity_metadata_rewrite" fixes this. 
Is it safe to disable that? I run more moded servers. 
What does it do exatcly and why it's important.

**Comment by electronicboy** [comment]
That setting disables the entity metadata rewriting in favor of sending a join packet to the client, basically; It offers a more robust solution for modded environments due to the fact that it doesn't rely on a mechanism that required being able to parse entity metadata, which the proxy needs to be able to understand (but can't)

**Comment by 123Kappa** [comment]
Thank you for the quick response!
Do you recommend disabling that? Can it cause issues? 

Also how do I find what mod causes this issue?

**Comment by electronicboy** [comment]
it serves to offer a much cleaner server switch to clients, but; There might be some plugin breakages due to them not expecting the changes involved

You would need to see if there is a way to get forge to dump the entity metadata registry or something, outside of tryna dissect your mods
