### ISSUE TITLE
initialhandler ddos throttle request

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Waterfall#528]
today my server got attacked, a bunch of proxies (all different IP so current throttle wouldnt catch) all requested to login with random usernames. This resulted in 50-700 connections per second during the attack and ultimately my bungee IP being blocked by mojang for a bit due to too many requests, as well as bungee freezing due to out of memory. This only took about a minute for the attacker. This could mitigated by adding a configurable rate limit to ANY join (InitialHandler has connected), I would suggest maybe 10 per second should be plenty? then any further connections for the rest of that second would just be completely ignored

also should be a option to ignore it for a configurable amount of time after a startup as thats when a lot of real players may join at once

**Comment by meadowsys** [comment]
maybe have the value in the config option. I think default 5-10 is about right, and for the startup period, a default of about 2 minutes ignored period is good

**Comment by electronicboy** [comment]
Currently taking some time off, so, probs not gonna really consider this for a little while

I'm not really fond of throwing in config options for this type of stuff, everybody is going to want different behaviors around this, that maintaining that in the core software is really not something I'm super happy fond about, especially when I recently added events to waterfall to allow plugins to handle with this as efficiently as possible, and saves us from having to care about every 'weird' request, e.g.

> for the startup period, a default of about 2 minutes ignored period is good

I mean, the way I see that, that is literally "I want a system to prevent this, but, I also don't want that system on startup because that's gonna blow", which is not really something I'd wanna care to permit, given that it, imho, defeats the entire purpose of this.

/really/, for stuff like this, it's probably worth actually looking into proper load balancing solutions, things like haproxy offer a *lot* of control over this stuff

**Comment by PhanaticD** [comment]
If every one wants different things isnt that exactly what config options are good for?

There is no way I'm going to set up all sorts of load balancing or whatever that I don't even think would work for a ddos attack that I would never need to do otherwise I only get like 100 players

If this is possible to actually cancel any sort of handling of the connection (before sending request to mojang at least) then that's fine this can be closed I'll try to make a plugin but if not I'd still like this to be considered

**Comment by JH3Y50N** [comment]
use an antibot... but not a normal antibot, try the JH_AntiBot v4 beta... https://cdn.discordapp.com/attachments/498363165520822292/719031333103468574/JH_AntiBot_v4.jar

**Comment by Janmm14** [comment]
@PhanaticD 
These two events run before mojang connection:

- PlayerHandshakeEvent
- PreLoginEvent

**Comment by PhanaticD** [comment]
I believe I have figured out how to do this with iptables, just posting it here for anyone to give it a second look as its not tested as I dont have this attack tool

to create:
```
# limit per IP first so that one person doesnt trigger the global limit
iptables -I INPUT -p tcp --dport 25565 -m state --state NEW -m recent --set
iptables -I INPUT -p tcp --dport 25565 -m state --state NEW -m recent --update --seconds 10 --hitcount 5 -j REJECT

# global limit of 10 new connections a second
iptables -N MCLIMIT
iptables -A INPUT -p tcp --dport 25565 -m state --state NEW -j MCLIMIT
iptables -A MCLIMIT -m limit --limit 10/s --limit-burst 20 -j ACCEPT
iptables -A MCLIMIT -j LOG --log-prefix "MCLIMIT: "
iptables -A MCLIMIT -j REJECT
```

then here is to remove:
```
iptables -D INPUT -p tcp --dport 25565 -m state --state NEW -m recent --set
iptables -D INPUT -p tcp --dport 25565 -m state --state NEW -m recent --update --seconds 10 --hitcount 5 -j REJECT

iptables -D INPUT -p tcp --dport 25565 -m state --state NEW -j MCLIMIT
iptables -D MCLIMIT -m limit --limit 10/s --limit-burst 20 -j ACCEPT
iptables -D MCLIMIT -j LOG --log-prefix "MCLIMIT: "
iptables -D MCLIMIT -j REJECT
iptables -F MCLIMIT
iptables -X MCLIMIT
```

**Comment by Janmm14** [comment]
The thing with iptables is that it does not differentiate between ping attempts and join attempts. You could do this with both events.
