### ISSUE TITLE
Susceptible to some form of DDOS crashing waterfall (Incorrect magic!) 

### ISSUE THREAD

**Issue by TomLewis** [PaperMC/Waterfall#565]
Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:52a5c6f:371 by md_5  

Ive suddenly today had a lot of bungee crashes, which is odd as nothing has changed in months with my waterfall it just sits there, one of my admins mentioned some kid saying "Ill send more packets in a second than you've had hot dinners", pulled the logs for waterfall and its nothing like ive ever seem, 200,000+ 
Here is **1 seconds** worth of logs:
https://gist.github.com/TomLewis/6c4433bdf72dfc1e4196dd8afa5fc12d

Whatever they are doing seems to work 100% of the time and times everyone out on the whole network, finally crashing itself.

I have found this, which Im going to install:
https://www.spigotmc.org/resources/pinglimiter-protection-against-layer-7-attacks-bungee-waterfall.72596/

No idea if this will solve it, would it be possible to get some form of fix for this type of attack that takes down the bungee 100% of the time?

**Comment by Chew** [comment]
Seems pretty illegal if you ask me...

**Comment by Janmm14** [comment]
Do you need to have Query protocol enabled at all?

**Comment by derklaro** [comment]
Nice IP leak

**Comment by Janmm14** [comment]
> 
> 
> Nice IP leak

I think that does not matter - I'm sure all those IPs are spoofed as query is udp based.

Edit: Randomly checking IPs I even found an IP from akamai's cdn network - this is definitely spoofed.

**Comment by TomLewis** [comment]
> 
> 
> Do you need to have Query protocol enabled at all?

Yeah I do to show online players on my website/Vote list websites can track players for better ranking.

How on earth is it possible to spoof an IP!?

**Comment by electronicboy** [comment]
> How on earth is it possible to spoof an IP!?

Query is UDP, don't need any form of handshake here

At the end of the day, a piece of software exposed to the internet has one job: to process connections
The only way we could solve this is by attempting to perform stuff like connection rate limiting, which due to the scope of, is
1) Better handled by the firewall of your server, iptables, etc
2) failing that, much better for a plugin to deal with given the nature of configurability required for stuff like this, it's not really realistic for us to perform this

**Comment by TomLewis** [comment]
> 
> 
> > How on earth is it possible to spoof an IP!?
> 
> Query is UDP, don't need any form of handshake here
> 
> At the end of the day, a piece of software exposed to the internet has one job: to process connections
> The only way we could solve this is by attempting to perform stuff like connection rate limiting, which due to the scope of, is
> 
>     1. Better handled by the firewall of your server, iptables, etc
> 
>     2. failing that, much better for a plugin to deal with given the nature of configurability required for stuff like this, it's not really realistic for us to perform this

Oof, this effects every single bungee/waterfall server that can be crashed by a script kiddy with whatever piece of software they have their hands on. 

These "Magic" queries are not legitimate queries, only process legitimate queries is one step in the right direction, the second one is limit the size of packets, third thing have a variable for setting X packets per second, theres no way anyone is getting legitimate queries like this a second.

At least tell me what I need to do in the firewall or link me to a plugin to fix this massive issue, anyone can crash the waterfall at any point... this isnt solved...

**Comment by Proximyst** [comment]
Just firewall off the port for all but some IPs (vote lists), and have some endpoint such as `/api/query` returning server info for your website. You can trust the vote sites, and your own code.

**Comment by TomLewis** [comment]
> Just firewall off the port for all but some IPs (vote lists), and have some endpoint such as `/api/query` returning server info for your website. You can trust the vote sites, and your own code.

But I already do that, I only have open ports that I need on the firewall.... Literally makes no sense why those IPs have random port numbers on them in the logs.

And you're saying to turn off query on the server?
The vote websites will all query in the same way, I would have to reverse engineer the minecraft query to solve a bug in bungee.

**Comment by mikroskeem** [comment]
What solution would you like to have? Mitigating attacks at application layer is too inefficient and must be done at lower layer (your best option - firewall). Query protocol has always been vulnerable to such attacks, your best solution is to firewall it off from others, or turn it off completely, as suggested multiple times already.

> I would have to reverse engineer the minecraft query to solve a bug in bungee.

No you don't, it's already [documentated](https://wiki.vg/Query)

**Comment by TomLewis** [comment]
> Query protocol has always been vulnerable to such attacks

Surely this should be a priority to get fixed then.

Or at the very least link me an alternative plugin that replaces the query that isn't vulnerable, if its always been a problem then someone would have by now created an alternative. Its vital to Vote list websites.

**Comment by Proximyst** [comment]
Read the answers above. I'm locking as you seem to want to selectively read.

**Comment by electronicboy** [comment]
> These "Magic" queries are not legitimate queries, only process legitimate queries is one step in the right direction

That's exactly what is happening with the invalid magic message

> the second one is limit the size of packets

At this point, size checks are 100% useless, this would be a micro-optimization at best, the memory and resources required to handle this packet have already been allocated, the existing logic to catch these will drop these packets from being responded to, as is already happening

> At least tell me what I need to do in the firewall or link me to a plugin to fix this massive issue, anyone can crash the waterfall at any point

Depends on your OS, system/firewall configuration issues are outside of the realms of this tracker, use the official support channels

> > Query protocol has always been vulnerable to such attacks

> Surely this should be a priority to get fixed then.
----
> But I already do that, I only have open ports that I need on the firewall.... Literally makes no sense why those IPs have random port numbers on them in the logs

Those open ports are exactly the issue here, the query protocol uses UDP which literally opens a giant gaping hole to the network, UDP packets are so stupidly cheap to send and offer 0 guarantees as to the sender, etc; vs the modern protocol designed to replace the query protocol uses TCP, which makes the whole act much more of a pain, the fact that this traffic is processed by the software is going to hurt, there is very little gain here at this point from the level of waterfall, this is better handled by a proper firewall, vs trying to scapegoat a firewall into waterfall at the wrong level, I'm willing to work with people who believe that they're willing to deal with all the caveats of a plugin level firewall, but, really, it's far too late for most use-cases and not something I have a personal interest in trying to maintain given the issues it tends to cause, including but not limited to acts such as taking advantage of it to perform a DoS attack. Those ports are also the source port for the UDP traffic, they have nothing to do with the ports on your machine.


At the end of the day, dealing with this in a clean manner at software level is essentially a complete waste of time and energy, the gains will be trivial at best as we wouldn't be able to reduce much of the actual overall work being done here. Really, you need to take steps to protect the query port at the correct level.

**Comment by electronicboy** [comment]
Also, quick 2 second look at pinglimiter suggests that it doesn't even deal with query packets at all

**Comment by aikar** [comment]
also note that ping server lists use is the TCP based one, not the UDP one. SOME of them might use the UDP one for optional extra data, but this is pure fluff and unnecessary.

Ran a server for many years and never used the UDP query protocol.
