### ISSUE TITLE
Waterfall doesn't announce version to the game

### ISSUE THREAD

**Issue by Polda18** [PaperMC/Waterfall#581]
Hi folks. For some reason Waterfall doesn't announce any sort of version to the game. Do we need to install an additional tool for this or is this a bug? If we write the version specifically to the `config.yml` file and restart the server, the game still doesn't detect it. Every other server (not ours) have the version detected by the game, even when they're using Bungee network. But our server kind of doesn't. We are using Waterfall + Paper 1.16.4, along with AdvancedNMotd plugin, which only customizes MOTD for the server. Disabling the plugin did nothing to the version not being detected properly.

**Comment by electronicboy** [comment]
This is a side-effect of how bungee works, it quite simply can't know what version the server is, especially with features like priority lists meaning that you could have multiple versions of the game, nor do we have a 'stable' mapping to game versions, there are many cases where the protocol version is used for multiple versions of the game, etc

However, waterfall.yml does have an option to let you throw a string in there for the messages, but the protocol version is separate, which most people just use things like ping-passthrough so that the backend server can deal with it, or find some plugin which lets them configure that stuff

**Comment by Polda18** [comment]
Well, the thing is that server list website made up versions on its own accord saying 1.8.x-1.16.x, while the server is only 1.16.4 (lower versions are unable to join), misleading new players. So unless there are some ways to recover info about each server (mainly the lobby server used to connect ot every other server in network), the information on the server list website will be misleading.

**Comment by electronicboy** [comment]
waterfall.yml has an option in there to let you set the string that is sent, as for actual protocol version in pings, either use ping passthrough or find a plugin which lets you control the supported protocol versions

**Comment by Polda18** [comment]
Okay, I'll look into it then. Thank you :)
