### ISSUE TITLE
failed to lookup papermc version error: 404

### ISSUE THREAD

**Issue by yogi7777** [PaperMC/Waterfall#646]
After reboot the Server, I can't start Waterfall:

failed to lookup papermc version error: 404

what can I do?

**Comment by electronicboy** [comment]
logs?

**Comment by yogi7777** [comment]
> logs?
i don't have more logs. the server does not starting

**Comment by electronicboy** [comment]
Is this actually a waterfall issue or a server issue?
The paper API is currently down due to some outage, this should not however impact startup, if it does that's a bug; There will still generally be a log file generated even if it crashes early, otherwise, copy the contents of the console (or, pipe the output to a file, specifics depends on your OS)

**Comment by yogi7777** [comment]
i have now Bungecoord startet. I works without Problems. But Waterfall not. I'm testing this evening on a other system. 
PS: I work with docker

**Comment by electronicboy** [comment]
closing, if you can't provide the info I've asked for I can't diagnose the issue
https://keybase.pub/electronicboy/builds/waterfall/waterfall-bus.zip | Build available here might work in the meantime
