### ISSUE TITLE
Teleporting Issue

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Waterfall#652]
https://github.com/masagameplay/MaSuiteWarps/issues/15

Waterfall might changed something that broke the cross server teleportation.

**Comment by Xernium** [comment]
There have been no changes to the logic here in months. If anything you should open an issue downstream on bungeecord in this case because Waterfall doesn’t really modify logic here. Plus unless you have actual evidence that Waterfall is at fault, or describe a reliable way to reproduce this problem, this issue is invalid.
