### ISSUE TITLE
Players can't reconnect because still considered connected

### ISSUE THREAD

**Issue by mgl** [PaperMC/Waterfall#69]
On Waterfall server some players are always shown as connected even if they are not. So if the player tries to reconnect he gets kicked because he is already connected, it happens randomly with some players.
The /glist returns player name like if he was connected and it causes severe bugs with other bungee plugins.

Java: Oracle Java 1.8.0_101
Waterfall: latest build

**Comment by jamierocks** [comment]
We will need a list of all of your plugins.

**Comment by mgl** [comment]
Plugins:
- AntiMinimap
- BungeeAuthMeBridge
- BungeeMSG
- FastLogin
- HubMagic
- LiteBans
- myPing
- ServerListPLus
- Yamler

I switched to latest classic bungeecord and this bugs doesn't happen so it's probably waterfall related.

**Comment by jamierocks** [comment]
Anyone able to confirm if this is still an issue?

**Comment by mgl** [comment]
Issue still exists in latest Waterfall.

**Comment by sgdc3** [comment]
Same issue, at the end of the day i can see around 40-50 "ghost" players in my lobbies.

**Comment by Jay9519** [comment]
it was happening on my server also, I removed the movemenow plugin so players would get disconnected when leaving a server instead of going to the lobby, no more ghosts

**Comment by Janmm14** [comment]
@Jay9519 Thanks for this information bit, this might help a lot. We experience the same issue using bungeecord and not waterfall. I'll probably have to take a look at our bungee plugin which has a similar behaviour to mocemenow and people recently reported this issue.

**Comment by sgdc3** [comment]
@Janmm14 With bungee i have no issues, the problem happens with waterfall + playerbalancer (lobby balancer + movemenow)

**Comment by Fluxty** [comment]
This issue is happening with me. We just switched to Waterfall today and this ghosting issue is now happening. Did a quick google search and this is our situation. Not sure if players can't connect because of it though, but it is highly concerning. Latest HubMagic-0.2.6. Seems when we close a lobby the other lobby lags intensely as HubMagic is trying to move everyone over and tons of errors are thrown like these (in our lobby when the other tries to move everyone there on reboot):

http://pastebin.com/fWhH2WsM

Don't know if related, but we also get this: http://pastebin.com/sZ50FVaA

So far I can say this is only happening in the lobby servers and not anywhere else, so the issue seems to be with HubMagic and WaterFall. We are also using CentOS and have the same startup message as this: https://github.com/WaterfallMC/Waterfall/issues/32

Wondering if compiling properly with CentOS can solve this? ^^ Thank you

**Comment by Fluxty** [comment]
Woke up, it's already built up over 100 ghost players per lobby and it's starting to eat the cpu

**Comment by Fluxty** [comment]
When using waterfall + hubmagic, try disconnecting from a gameserver. You will see the player pop up in the lobby/fallback for a brief time before disappearing. In the case of high traffic, sometimes the player pops up in the lobby after completely disconnecting from the proxy but is never removed from the lobby. The same applies when connecting to a gameserver. This is not observed on normal Bungeecord + HubMagic

**Comment by sgdc3** [comment]
same there, it happens with lobbybalancer (premium version of hubmagic) but the dev checked the code multiple times and works with bungee.

**Comment by Fluxty** [comment]
Just an update, we have grown quite a lot and have switched hosts. Our lobbies are spread across 6 dedis, all running Ubuntu . With HubMagic + Waterfall (and RedisBungee) we still experience "ghost" players in our lobbies. Waterfall never lets go of player objects, you can /find anyone who's been online since the last reboot and they'll be in one of our lobbies. Luckily the lobbies do not overflow with players like they did in the past, but I believe its greatly contributing to our memory usage on Bungee and forcing us to do reboots more often than we'd like to.

**Comment by Beaast-exe** [comment]
Got this issue today, disconnected and cant reconnect
You are already connected to this proxy

**Comment by Beaast-exe** [comment]
After some investigation it looks like the problems has it's source from a server connected to the Proxy, and not the Proxy itself, for the server, I didn't disconnect.
