### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by sgdc3** [PaperMC/Waterfall#7]
why? just... why?

**Comment by kamcio96** [comment]
What "why"?

**Comment by sgdc3** [comment]
Why patch based? What are the advantages?

**Comment by sgdc3** [comment]
I think that if the project aims to be collaboration oriented clean source is better.

**Comment by kamcio96** [comment]
Faster recompile, faster changes review

**Comment by sgdc3** [comment]
Yeah but less people working on it.

**Comment by kamcio96** [comment]
you can download jar from CI

**Comment by sgdc3** [comment]
I'm talking about PRs

**Comment by kamcio96** [comment]
There is rebuildPatches.sh script

**Comment by sgdc3** [comment]
this is just an useless complexity

**Comment by kamcio96** [comment]
join to our irc :wink:

**Comment by sgdc3** [comment]
nevermind, the project is yours... let it became like spigot (collaborative -110%)

**Comment by phase** [comment]
I'd argue it's easier for everyone. It makes it easy to merge commits with Bungeecord. Once you have the environment setup, it's easy to submit changes. Learn how to use git before you start complaining.

**Comment by sgdc3** [comment]
It's not for me, i know how the patches works, in my opinion in this way everyone who isn't a git expert is unable to contribute to the project.

**Comment by phase** [comment]
They are completely _able_ to contribute. If they don't want to learn how to use git then they probably don't know enough to contribute good code.

**Comment by sgdc3** [comment]
Contributing should be easy, this is the purpose of github.

**Comment by phase** [comment]
GitHub is a git hosting site. It does not guarantee that contributing to a project will be the easiest thing in the world. It is _easy enough_ to submit changes with this patch system. Obviously, a separate code base is easier for skids to hack, but a patch system makes it easy to merge upstream.

**Comment by kamcio96** [comment]
But, what is hard in patches? Just change project code, rebuildPatches.sh, git commit, git push

**Comment by Techcable** [comment]
We agreed to switch to a patch based system because it allows us to easily see and manage the diff with upstream.
It also allows us to easily merge upstream (it got very complicated in the old system).
Once you know how to contribute, its easy, although we should add a guide #10.

Making a large contribution to waterfall already has a relatively high barrier of entry, and switching back to the old system won't make it that much easier.
We will _not_ be switching back to the old system just to slightly reduce the learning curve for contributing small patches to the repo.

If have a serious concern, bring it up on IRC, but don't complain about it being to hard.
