### ISSUE TITLE
Custom BC names

### ISSUE THREAD

**Issue by Arobcher** [PaperMC/Waterfall#96]
Excuse me, you can add in Config.yml add
custom_server_name
custom_server_name: YourBungeeName

This setting allows you to set a very cool or unique BungeeCord name, as well as he will be displayed in Motd above
For example, version 1.6.4 can not connect to BC server, but he can see
Waterfall 1.8.x, 1.9.x, 1.10.x~
When you change the CSN
For example: custom_server_name: SuperBungee or more

If you think this is a good suggestion, I hope to use! Thank you
And can also be added within the Travertine BungeeCord

**Comment by RoboMWM** [comment]
Why? If you really want to report a custom name for the software you're running, why not just fork it and **customize** it yourself? Otherwise it seems somewhat disingenuous to simply stick your network/whatever name on a software that has no contributions from you/your network...

Also see my reply here: https://aquifermc.org/threads/plugin-to-spoof-query-packet.357/#post-2117

**Comment by jamierocks** [comment]
Yeah, we're not doing this.
That shows the software being used, if you want it changed fork Waterfall.

**Comment by Janmm14** [comment]
Or use some server pi g plugins to modify that.
